# .github/workflows/ci-cd.yml
name: ci-cd

on:
  on:
    push:
      branches:
        - main

  # pull_request:
  #   branches:
  #     - main

#comment just to see if this work

jobs:
  format:
    uses: ./.github/workflows/ci-format.yml

  test:
    needs: format
    uses: ./.github/workflows/ci-tests.yml